from typing import Tuple
import numpy as np
from numpy.typing import NDArray

def flux_x_py(q: NDArray, gamma: float) -> NDArray: ...
def flux_y_py(q: NDArray, gamma: float) -> NDArray: ...
def con2primi_py(q: NDArray, gamma: float) -> Tuple[NDArray, NDArray, NDArray, NDArray, NDArray, NDArray]: ...
def weno_x_py(u: NDArray, gamma: float) -> Tuple[NDArray, NDArray, NDArray, NDArray]: ...
def weno_y_py(u: NDArray, gamma: float) -> Tuple[NDArray, NDArray, NDArray, NDArray]: ...
def hllc_x_rs_py(q_l: NDArray, q_r: NDArray, f_l: NDArray, f_r: NDArray, gamma: float) -> NDArray: ...
def hllc_y_rs_py(q_l: NDArray, q_r: NDArray, f_l: NDArray, f_r: NDArray, gamma: float) -> NDArray: ...
def l_local_py(u:NDArray, dx: float, gamma: float, force_hlle: bool, jp_cri: tuple) -> NDArray: ...